export const categories_ = [
    "Books",
    "Clothing",
    "Electronics",
    "Furniture",
    "Home Appliances",
    "Toys & Games",
    "Sports Equipment",
    "Musical Instruments",
    "Stationery",
    "Pet Supplies",
    "Beauty & Personal Care",
    "Baby Products",
    "Tools & Hardware",
    "Art & Craft",
    "Bags & Accessories",
    "Footwear",
    "Mobile Phones & Accessories",
    "Bicycles",
    "Gardening",
    "Other",
  ];
  export const city = [
    "Mumbai",
    "Delhi",
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Ahmedabad",
    "Jaipur",
    "Lucknow",
    "Chandigarh",
    "Surat",
    "Indore",
    "Nagpur",
    "Bhopal",
    "Patna",
    "Thiruvananthapuram",
    "Kochi",
    "Visakhapatnam",
    "Vadodara",
    "Ranchi",
    "Raipur",
    "Guwahati",
    "Noida",
    "Gurugram",
    "other",
  ];